#!/bin/bash

brightness=$(brightnessctl | grep -oP '\(\d{1,3}%\)')

echo "$brightness"
# exit

brightness="${brightness#?}"
brightness="${brightness%??}"

echo "$brightness"

if [[ "$1" == "increase" && "$brightness" != "100" ]]; then
  brightness=$((brightness + 5))
  brightnessctl set "$brightness%"
elif [[ "$1" == "decrease" && "$brightness" != "0" ]]; then
  brightness=$((brightness - 5))
  brightnessctl set "$brightness%"
fi

brightness=$(brightnessctl | grep -oP '\(\d{1,3}%\)')
brightness="${brightness#?}"
brightness="${brightness%??}"
dunstify -a "ignored" -r 9993 -h int:value:"$brightness" "Brightness: $brightness%" -t 500



