#!/bin/bash

pactl set-sink-mute @DEFAULT_SINK@ toggle

muted=$(pactl list sinks | grep -A 15 "$(pactl info | grep 'Default Sink:' | awk '{print $3}')" | grep 'Mute:' | awk '{print $2}')


if [[ "$muted" == "yes" ]]; then 
  dunstify -r 9994 -h int:value:"0" "Volume: Muted" -t 500
else
  volume=$(pactl get-sink-volume @DEFAULT_SINK@)
  volume=$(echo "$volume" | grep -oP "\d{1,3}%" | uniq)
  volume="${volume%?}"
  dunstify -r 9994 -h int:value:"$volume" "Volume: $volume%" -t 500
fi



