#!/bin/bash

volume=$(pactl get-sink-volume @DEFAULT_SINK@)
volume=$(echo "$volume" | grep -oP "\d{1,3}%" | uniq)

volume="${volume%?}"

if [[ "$1" == "increase" && "$volume" -lt "150" ]]; then
  volume=$((volume + 10))
  pactl set-sink-volume @DEFAULT_SINK@ "$volume"% 
elif [[ "$1" == "decrease" && "$volume" != "0" ]]; then
  volume=$((volume - 10))
  pactl set-sink-volume @DEFAULT_SINK@ "$volume"% 
fi

volume=$(pactl get-sink-volume @DEFAULT_SINK@)
volume=$(echo "$volume" | grep -oP "\d{1,3}%" | uniq)

volume="${volume%?}"

 
dunstify -a  "ignored" -r 9994 -h int:value:"$volume" "Volume: $volume%" -t 500


