#!/bin/bash

brightness=$(brightnessctl | grep -oP '\(\d{1,3}%\)')

echo "$brightness"
# exit

brightness="${brightness#?}"
brightness="${brightness%??}"

echo "$brightness"

if [[ "$1" == "increase" && "$brightness" != "100" ]]; then
  brightness=$((brightness + 5))
  brightnessctl set "$brightness%"
elif [[ "$1" == "decrease" && "$brightness" != "0" ]]; then
  brightness=$((brightness - 5))
  brightnessctl set "$brightness%"
fi

brightness=$(brightnessctl | grep -oP '\(\d{1,3}%\)')
brightness="${brightness#?}"
brightness="${brightness%??}"


id=$(cat /$HOME/.config/sway/scripts/brightness_id.txt)
if [ "$id" == "" ]; then 
  id=$(notify-send -e -p -t 500 -h int:value:"$brightness" "Brightness: $brightness%")
  echo "$id" > /$HOME/.config/sway/scripts/brightness_id.txt
  echo "not_set"
else
  notify-send -e -r "$id" -t 500 -h int:value:"$brightness" "Brightness: $brightness%" 
  echo "came here"
fi


