#!/bin/bash

# parent_container=$(i3-msg -t get_tree | jq -r 'recurse( .nodes[];.nodes!=null) | select( .nodes[].focused )')



parent_container=$(i3-msg -t get_tree | jq -r 'recurse(.nodes[];.nodes!=null)|select(.nodes[].focused)')

echo "$parent_container"

