#!/bin/bash


result=$(bluetoothctl power on)
result_check=$(echo "$result" | grep -oP "Changing power on succeeded")


if [[ "$result_check" != "Changing power on succeeded" ]]; then
  dunstify -u critical "Bluetooth" "Failed to power on:\n$result"
  exit
fi

blueman-manager &


