#!/bin/bash


device_list=$(bluetoothctl devices Paired) 
device_names=$(echo "$device_list" | cut -d ' ' -f 3-)
selection=$(echo -e "$device_names" | dmenu -i -l 10 -p "Device to Remove:")

if [[ "$selection" == "" ]]; then 
  exit
fi

mac=$(echo "$device_list" | grep "$selection" | awk '{print $2}')

echo "$mac"


disconnect_result=$(bluetoothctl disconnect "$mac")
result_check=$(echo "$disconnect_result" | grep -oP "Successful disconnected")

if [[ "$result_check" != "Successful disconnected" ]]; then
  echo "came here lmao"
  dunstify -u critical "Bluetooth" "Failed to disconnect $selection\n$disconnect_result"
  exit
fi


remove_result=$(bluetoothctl remove "$mac")


echo "$result"

result_check=$(echo "$remove_result" | grep -oP "Device has been removed")

if [[ "$result_check" != "Device has been removed" ]]; then
  dunstify -u critical "Bluetooth" "Failed to remove $selection\n$remove_result"
  exit
fi

dunstify "Bluetooth" "Removed $selection"

